//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SprTable()
        {
            this.UchTable = new HashSet<UchTable>();
        }
    
        public int Cod_Pred { get; set; }
        public string Name_Pred { get; set; }
        public string Adres { get; set; }
        public string FIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UchTable> UchTable { get; set; }
    }
}
