//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UchTable
    {
        public int Num_z { get; set; }
        public int Cod_Pred { get; set; }
        public string Name_Product { get; set; }
        public int Kol_vo { get; set; }
        public int Price { get; set; }
    
        public virtual SprTable SprTable { get; set; }
    }
}
